import { NextResponse } from "next/server"

const MOCK_DATA = {
  cities: {
    Lahore: {
      authorities: {
        LDA: {
          plot_sizes: {
            "3-marla": {
              meta: {
                plot_size_label: "3 Marla",
                authority: "LDA",
                city: "Lahore",
                frontend_key: "3-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 38,
                ground_coverage_percent: 85,
                FAR: "1:2",
                mandatory_open_spaces: {
                  front: "5 ft",
                  rear: "N/A",
                  side: "N/A",
                },
                bedrooms_range: { min: 1, max: 5 },
                washrooms_range: { min: 2, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Family Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: {
                  servant_quarter: false,
                  swimming_pool: false,
                  basement: false,
                  mumty: true,
                },
                parking: {
                  type: "Not Required",
                  spaces: 0,
                },
                special_rules: [
                  "Ground floor bedroom maximum: 1",
                  "First floor bedroom maximum: 2",
                  "Second floor bedroom maximum: 2",
                  "No garage allowed due to space constraints",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: {
                plot_size_label: "5 Marla",
                authority: "LDA",
                city: "Lahore",
                frontend_key: "5-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 38,
                ground_coverage_percent: 80,
                FAR: "1:1.6",
                mandatory_open_spaces: {
                  front: "5 ft",
                  rear: "5 ft",
                  side: "N/A",
                },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Family Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: {
                  servant_quarter: false,
                  swimming_pool: false,
                  basement: false,
                  mumty: true,
                },
                parking: {
                  type: "Single Car Garage",
                  spaces: 1,
                },
                special_rules: [
                  "Ground floor bedroom maximum: 1",
                  "First floor bedroom maximum: 2",
                  "Second floor bedroom maximum: 2",
                  "Garage mandatory on ground floor",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: {
                plot_size_label: "7 Marla",
                authority: "LDA",
                city: "Lahore",
                frontend_key: "7-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 38,
                ground_coverage_percent: 80,
                FAR: "1:1.6",
                mandatory_open_spaces: {
                  front: "5 ft",
                  rear: "5 ft",
                  side: "3 ft (one side)",
                },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Family Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: {
                  servant_quarter: false,
                  swimming_pool: false,
                  basement: false,
                  mumty: true,
                },
                parking: {
                  type: "Single Car Garage",
                  spaces: 1,
                },
                special_rules: [
                  "Ground floor bedroom maximum: 1",
                  "First floor bedroom maximum: 2",
                  "Second floor bedroom maximum: 2",
                  "Side setback required on one side",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "10-marla": {
              meta: {
                plot_size_label: "10 Marla",
                authority: "LDA",
                city: "Lahore",
                frontend_key: "10-marla",
              },
              available_options: {
                max_floors: 4,
                max_height_ft: 45,
                ground_coverage_percent: 70,
                FAR: "1:2.8",
                mandatory_open_spaces: {
                  front: "10 ft",
                  rear: "7 ft",
                  side: "5 ft (one side)",
                },
                bedrooms_range: { min: 3, max: 6 },
                washrooms_range: { min: 4, max: 8 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Family Room", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen", "Modular Kitchen"],
                allowed_features: {
                  servant_quarter: true,
                  swimming_pool: false,
                  basement: false,
                  mumty: true,
                },
                parking: {
                  type: "Single/Double Car Garage",
                  min: 1,
                  max: 2,
                },
                special_rules: [
                  "Ground floor bedroom maximum: 2",
                  "First floor bedroom maximum: 2",
                  "Second floor bedroom maximum: 2",
                  "Mandatory greywater tank installation",
                  "Setback law reinstated",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: {
                plot_size_label: "1 Kanal",
                authority: "LDA",
                city: "Lahore",
                frontend_key: "1-kanal",
              },
              available_options: {
                max_floors: 4,
                max_height_ft: 45,
                ground_coverage_percent: 65,
                FAR: "1:2.6",
                mandatory_open_spaces: {
                  front: "10 ft",
                  rear: "7 ft",
                  side: "5 ft (both sides)",
                },
                bedrooms_range: { min: 4, max: 10 },
                washrooms_range: { min: 5, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Family Room", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen", "Modular Kitchen"],
                allowed_features: {
                  servant_quarter: true,
                  swimming_pool: true,
                  basement: false,
                  mumty: true,
                },
                parking: {
                  type: "Double Car Garage",
                  min: 2,
                  max: 3,
                },
                special_rules: [
                  "Ground floor bedroom maximum: 3",
                  "First floor bedroom maximum: 4",
                  "Second floor bedroom maximum: 3",
                  "Mandatory greywater tank installation",
                  "Setback law reinstated",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: {
                plot_size_label: "2 Kanal",
                authority: "LDA",
                city: "Lahore",
                frontend_key: "2-kanal",
              },
              available_options: {
                max_floors: 4,
                max_height_ft: 45,
                ground_coverage_percent: 55,
                FAR: "1:2.2",
                mandatory_open_spaces: {
                  front: "20 ft",
                  rear: "10 ft",
                  side: "10 ft (both sides)",
                },
                bedrooms_range: { min: 5, max: 12 },
                washrooms_range: { min: 6, max: 15 },
                public_zones: [
                  "Lounge",
                  "Drawing Room",
                  "TV Lounge",
                  "Family Room",
                  "Study Room",
                  "Library",
                  "Guest Room",
                ],
                service_zones: [
                  "Kitchen",
                  "Store",
                  "Laundry",
                  "Servant Quarter",
                  "Garage",
                  "Generator Room",
                  "Security Room",
                ],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen", "Modular Kitchen"],
                allowed_features: {
                  servant_quarter: true,
                  swimming_pool: true,
                  basement: false,
                  mumty: true,
                },
                parking: {
                  type: "Multiple Car Garage",
                  min: 3,
                  max: 5,
                },
                special_rules: [
                  "Ground floor bedroom maximum: 4",
                  "First floor bedroom maximum: 4",
                  "Second floor bedroom maximum: 4",
                  "Mandatory greywater tank installation",
                  "Setback law reinstated",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
        DHA: {
          plot_sizes: {
            "3-marla": {
              meta: { plot_size_label: "3 Marla", authority: "DHA", city: "Lahore", frontend_key: "3-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 80,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: { plot_size_label: "5 Marla", authority: "DHA", city: "Lahore", frontend_key: "5-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: { plot_size_label: "7 Marla", authority: "DHA", city: "Lahore", frontend_key: "7-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "10-marla": {
              meta: { plot_size_label: "10 Marla", authority: "DHA", city: "Lahore", frontend_key: "10-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 70,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (one side)" },
                bedrooms_range: { min: 3, max: 6 },
                washrooms_range: { min: 4, max: 8 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single/Double Car Garage", min: 1, max: 2 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: { plot_size_label: "1 Kanal", authority: "DHA", city: "Lahore", frontend_key: "1-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: { plot_size_label: "2 Kanal", authority: "DHA", city: "Lahore", frontend_key: "2-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:1.4",
                mandatory_open_spaces: { front: "15 ft", rear: "10 ft", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 4 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
        "Bahria Town": {
          plot_sizes: {
            "3-marla": {
              meta: { plot_size_label: "3 Marla", authority: "Bahria Town", city: "Lahore", frontend_key: "3-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 80,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: { plot_size_label: "5 Marla", authority: "Bahria Town", city: "Lahore", frontend_key: "5-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: { plot_size_label: "7 Marla", authority: "Bahria Town", city: "Lahore", frontend_key: "7-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "10-marla": {
              meta: { plot_size_label: "10 Marla", authority: "Bahria Town", city: "Lahore", frontend_key: "10-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 70,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (one side)" },
                bedrooms_range: { min: 3, max: 6 },
                washrooms_range: { min: 4, max: 8 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single/Double Car Garage", min: 1, max: 2 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: { plot_size_label: "1 Kanal", authority: "Bahria Town", city: "Lahore", frontend_key: "1-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: { plot_size_label: "2 Kanal", authority: "Bahria Town", city: "Lahore", frontend_key: "2-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:1.4",
                mandatory_open_spaces: { front: "15 ft", rear: "10 ft", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 4 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
      },
    },
    Karachi: {
      authorities: {
        KDA: {
          plot_sizes: {
            "3-marla": {
              meta: {
                plot_size_label: "3 Marla (60-119 sqyd)",
                authority: "KDA",
                city: "Karachi",
                frontend_key: "3-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 70,
                FAR: "1:2",
                mandatory_open_spaces: { front: "5 ft", rear: "Exempted", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["Rear COS exempted for plots ≤119 sq yd", "FAR override allowed"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: {
                plot_size_label: "5 Marla (120-199 sqyd)",
                authority: "KDA",
                city: "Karachi",
                frontend_key: "5-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:2",
                mandatory_open_spaces: { front: "5 ft", rear: "50% of COS", side: "N/A" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Rear COS: 50% of COS", "FAR override allowed"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: {
                plot_size_label: "7 Marla (200-399 sqyd)",
                authority: "KDA",
                city: "Karachi",
                frontend_key: "7-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:2",
                mandatory_open_spaces: { front: "5 ft", rear: "50% of COS", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Rear COS: 50% of COS", "FAR override allowed"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "10-marla": {
              meta: {
                plot_size_label: "10 Marla (400-999 sqyd)",
                authority: "KDA",
                city: "Karachi",
                frontend_key: "10-marla",
              },
              available_options: {
                max_floors: 2,
                max_height_ft: 25,
                ground_coverage_percent: 50,
                FAR: "1:1.5",
                mandatory_open_spaces: { front: "10 ft", rear: "50% of COS", side: "5 ft (one side)" },
                bedrooms_range: { min: 3, max: 8 },
                washrooms_range: { min: 4, max: 8 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: false, basement: true, mumty: true },
                parking: { type: "Single/Double Car Garage", min: 1, max: 2 },
                special_rules: ["Rear COS: 50% of COS", "Basement allowed", "FAR override allowed"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: {
                plot_size_label: "1 Kanal (400-999 sqyd)",
                authority: "KDA",
                city: "Karachi",
                frontend_key: "1-kanal",
              },
              available_options: {
                max_floors: 2,
                max_height_ft: 25,
                ground_coverage_percent: 50,
                FAR: "1:1.5",
                mandatory_open_spaces: { front: "10 ft", rear: "50% of COS", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: true, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["Rear COS: 50% of COS", "Basement allowed", "FAR override allowed"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: {
                plot_size_label: "2 Kanal (1000+ sqyd)",
                authority: "KDA",
                city: "Karachi",
                frontend_key: "2-kanal",
              },
              available_options: {
                max_floors: 2,
                max_height_ft: 25,
                ground_coverage_percent: 45,
                FAR: "1:1.2",
                mandatory_open_spaces: { front: "15 ft", rear: "50% of COS", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: true, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 5 },
                special_rules: ["Rear COS: 50% of COS", "Basement allowed", "FAR override allowed"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
        DHA: {
          plot_sizes: {
            "3-marla": {
              meta: { plot_size_label: "3 Marla", authority: "DHA", city: "Karachi", frontend_key: "3-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 80,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: { plot_size_label: "5 Marla", authority: "DHA", city: "Karachi", frontend_key: "5-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: { plot_size_label: "7 Marla", authority: "DHA", city: "Karachi", frontend_key: "7-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "10-marla": {
              meta: { plot_size_label: "10 Marla", authority: "DHA", city: "Karachi", frontend_key: "10-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 70,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (one side)" },
                bedrooms_range: { min: 3, max: 6 },
                washrooms_range: { min: 4, max: 8 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single/Double Car Garage", min: 1, max: 2 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: { plot_size_label: "1 Kanal", authority: "DHA", city: "Karachi", frontend_key: "1-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: { plot_size_label: "2 Kanal", authority: "DHA", city: "Karachi", frontend_key: "2-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:1.4",
                mandatory_open_spaces: { front: "15 ft", rear: "10 ft", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 4 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
        "Bahria Town": {
          plot_sizes: {
            "3-marla": {
              meta: { plot_size_label: "3 Marla", authority: "Bahria Town", city: "Karachi", frontend_key: "3-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 80,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: { plot_size_label: "5 Marla", authority: "Bahria Town", city: "Karachi", frontend_key: "5-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: { plot_size_label: "7 Marla", authority: "Bahria Town", city: "Karachi", frontend_key: "7-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "10-marla": {
              meta: {
                plot_size_label: "10 Marla",
                authority: "Bahria Town",
                city: "Karachi",
                frontend_key: "10-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 70,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (one side)" },
                bedrooms_range: { min: 3, max: 6 },
                washrooms_range: { min: 4, max: 8 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single/Double Car Garage", min: 1, max: 2 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: { plot_size_label: "1 Kanal", authority: "Bahria Town", city: "Karachi", frontend_key: "1-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: { plot_size_label: "2 Kanal", authority: "Bahria Town", city: "Karachi", frontend_key: "2-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:1.4",
                mandatory_open_spaces: { front: "15 ft", rear: "10 ft", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 4 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
      },
    },
    Islamabad: {
      authorities: {
        CDA: {
          plot_sizes: {
            "3-marla": {
              meta: { plot_size_label: "3 Marla", authority: "CDA", city: "Islamabad", frontend_key: "3-marla" },
              available_options: {
                max_floors: 2,
                max_height_ft: 30,
                ground_coverage_percent: 60,
                FAR: "1:1.2",
                mandatory_open_spaces: { front: "30 ft frontage minimum", rear: "N/A", side: "5 ft" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["30 ft frontage minimum required", "CDA revised building regulations 2024"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: { plot_size_label: "5 Marla", authority: "CDA", city: "Islamabad", frontend_key: "5-marla" },
              available_options: {
                max_floors: 2,
                max_height_ft: 30,
                ground_coverage_percent: 60,
                FAR: "1:1.2",
                mandatory_open_spaces: { front: "30 ft frontage minimum", rear: "5 ft", side: "5 ft" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["30 ft frontage minimum required", "CDA revised building regulations 2024"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: { plot_size_label: "7 Marla", authority: "CDA", city: "Islamabad", frontend_key: "7-marla" },
              available_options: {
                max_floors: 2,
                max_height_ft: 30,
                ground_coverage_percent: 60,
                FAR: "1:1.05",
                mandatory_open_spaces: { front: "30 ft frontage minimum", rear: "5 ft", side: "5 ft (one side)" },
                bedrooms_range: { min: 2, max: 6 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["30 ft frontage minimum required", "CDA revised building regulations 2024"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: { plot_size_label: "1 Kanal", authority: "CDA", city: "Islamabad", frontend_key: "1-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 30,
                ground_coverage_percent: 50,
                FAR: "1:0.9",
                mandatory_open_spaces: { front: "30 ft frontage minimum", rear: "7 ft", side: "5 ft both sides" },
                bedrooms_range: { min: 3, max: 7 },
                washrooms_range: { min: 4, max: 9 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: [
                  "30 ft frontage minimum required",
                  "CDA revised building regulations 2024",
                  "Increased FAR for large plots",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: { plot_size_label: "2 Kanal", authority: "CDA", city: "Islamabad", frontend_key: "2-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 30,
                ground_coverage_percent: 50,
                FAR: "1:0.9",
                mandatory_open_spaces: { front: "30 ft frontage minimum", rear: "10 ft", side: "10 ft both sides" },
                bedrooms_range: { min: 4, max: 10 },
                washrooms_range: { min: 5, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 5 },
                special_rules: [
                  "30 ft frontage minimum required",
                  "CDA revised building regulations 2024",
                  "Increased FAR for large plots",
                ],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
        DHA: {
          plot_sizes: {
            "3-marla": {
              meta: { plot_size_label: "3 Marla", authority: "DHA", city: "Islamabad", frontend_key: "3-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 80,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: { plot_size_label: "5 Marla", authority: "DHA", city: "Islamabad", frontend_key: "5-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: { plot_size_label: "7 Marla", authority: "DHA", city: "Islamabad", frontend_key: "7-marla" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: { plot_size_label: "1 Kanal", authority: "DHA", city: "Islamabad", frontend_key: "1-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: { plot_size_label: "2 Kanal", authority: "DHA", city: "Islamabad", frontend_key: "2-kanal" },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:1.4",
                mandatory_open_spaces: { front: "15 ft", rear: "10 ft", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 4 },
                special_rules: ["DHA standard building regulations apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
        "Bahria Town": {
          plot_sizes: {
            "3-marla": {
              meta: {
                plot_size_label: "3 Marla",
                authority: "Bahria Town",
                city: "Islamabad",
                frontend_key: "3-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 80,
                FAR: "1:1.8",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "N/A" },
                bedrooms_range: { min: 1, max: 4 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Not Required", spaces: 0 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "5-marla": {
              meta: {
                plot_size_label: "5 Marla",
                authority: "Bahria Town",
                city: "Islamabad",
                frontend_key: "5-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 2, max: 5 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "7-marla": {
              meta: {
                plot_size_label: "7 Marla",
                authority: "Bahria Town",
                city: "Islamabad",
                frontend_key: "7-marla",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 75,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "5 ft", rear: "5 ft", side: "3 ft (one side)" },
                bedrooms_range: { min: 2, max: 5 },
                washrooms_range: { min: 3, max: 6 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge"],
                service_zones: ["Kitchen", "Store", "Laundry", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen"],
                allowed_features: { servant_quarter: false, swimming_pool: false, basement: false, mumty: true },
                parking: { type: "Single Car Garage", spaces: 1 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "1-kanal": {
              meta: {
                plot_size_label: "1 Kanal",
                authority: "Bahria Town",
                city: "Islamabad",
                frontend_key: "1-kanal",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 65,
                FAR: "1:1.6",
                mandatory_open_spaces: { front: "10 ft", rear: "7 ft", side: "5 ft (both sides)" },
                bedrooms_range: { min: 4, max: 8 },
                washrooms_range: { min: 5, max: 10 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Double Car Garage", min: 2, max: 3 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
            "2-kanal": {
              meta: {
                plot_size_label: "2 Kanal",
                authority: "Bahria Town",
                city: "Islamabad",
                frontend_key: "2-kanal",
              },
              available_options: {
                max_floors: 3,
                max_height_ft: 35,
                ground_coverage_percent: 60,
                FAR: "1:1.4",
                mandatory_open_spaces: { front: "15 ft", rear: "10 ft", side: "10 ft (both sides)" },
                bedrooms_range: { min: 5, max: 10 },
                washrooms_range: { min: 6, max: 12 },
                public_zones: ["Lounge", "Drawing Room", "TV Lounge", "Study Room", "Library", "Guest Room"],
                service_zones: ["Kitchen", "Store", "Laundry", "Servant Quarter", "Garage", "Generator Room"],
                kitchen_types: ["Open Kitchen", "Closed Kitchen", "Island Kitchen"],
                allowed_features: { servant_quarter: true, swimming_pool: true, basement: false, mumty: true },
                parking: { type: "Multiple Car Garage", min: 3, max: 4 },
                special_rules: ["Bahria Town architectural guidelines apply"],
                additional_rules: {},
              },
              raw_bylaws: {},
            },
          },
        },
      },
    },
  },
  global_options: {
    orientation: ["North", "South", "East", "West", "North-East", "North-West", "South-East", "South-West"],
    facing: ["Main Road", "Side Road", "Corner", "Back Lane"],
    shape: ["Regular", "Irregular", "Corner", "L-Shape"],
  },
}

export async function GET() {
  try {
    console.log("[v0] Mock API: Returning comprehensive form options data for all cities")
    return NextResponse.json(MOCK_DATA)
  } catch (error) {
    console.error("[v0] Error in mock form options API:", error)
    return NextResponse.json({ error: "Failed to fetch form options" }, { status: 500 })
  }
}
